# Generated by Django 4.2.7 on 2023-11-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0009_rename_accounts_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bio',
        ),
    ]
