# Generated by Django 4.2.7 on 2023-11-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0010_remove_account_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
