# Generated by Django 4.2.7 on 2023-11-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0011_account_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(max_length=200),
        ),
    ]
