# Generated by Django 4.2.7 on 2023-11-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0012_alter_account_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
