# Generated by Django 4.2.7 on 2023-11-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0014_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
    ]
