# Generated by Django 4.2.7 on 2023-11-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0016_alter_car_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
