# Generated by Django 4.2.7 on 2023-11-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0021_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
